### ISSUE TITLE
[Console Spam] 1.15.2

### ISSUE THREAD

**Issue by BedrockLegends** [McJtyMods/RFToolsStorage#10]
16.04 20:28:06 [Multicraft] ModernGamingWorld ran command: Say dont worry about the new update coming out shortly as for some fed reason it does not want to install on twitch
16.04 20:28:06 [Server] Server thread/FATAL Error executing task on Server
16.04 20:28:06 [Server] INFO java.lang.NullPointerException: null
16.04 20:28:06 [Server] mcjty.rftoolsstorage.craftinggrid.StorageCraftingTools.match(StorageCraftingTools.java:153) ~[?:1.15-1.0.3-alpha {re:classloading}
16.04 20:28:06 [Server] mcjty.rftoolsstorage.craftinggrid.StorageCraftingTools.tryRecipe(StorageCraftingTools.java:63) ~[?:1.15-1.0.3-alpha {re:classloading}
16.04 20:28:06 [Server] mcjty.rftoolsstorage.craftinggrid.StorageCraftingTools.lambda$testCraftItems$3(StorageCraftingTools.java:293) ~[?:1.15-1.0.3-alpha {re:classloading}
16.04 20:28:06 [Server] java.util.Optional.map(Optional.java:215) ~[?:1.8.0_241 {}
16.04 20:28:06 [Server] mcjty.rftoolsstorage.craftinggrid.StorageCraftingTools.testCraftItems(StorageCraftingTools.java:268) ~[?:1.15-1.0.3-alpha {re:classloading}
16.04 20:28:06 [Server] mcjty.rftoolsstorage.modules.modularstorage.blocks.ModularStorageTileEntity.craft(ModularStorageTileEntity.java:136) ~[?:1.15-1.0.3-alpha {re:classloading}
16.04 20:28:06 [Server] mcjty.rftoolsstorage.craftinggrid.StorageCraftingTools.craftFromGrid(StorageCraftingTools.java:330) ~[?:1.15-1.0.3-alpha {re:classloading}
16.04 20:28:06 [Server] mcjty.rftoolsstorage.setup.CommandHandler.lambda$registerCommands$5(CommandHandler.java:86) ~[?:1.15-1.0.3-alpha {re:classloading}
16.04 20:28:06 [Server] mcjty.lib.McJtyLib.handleCommand(McJtyLib.java:96) ~[?:1.15-4.0.3-alpha {re:classloading}
16.04 20:28:06 [Server] mcjty.lib.network.PacketSendServerCommand.lambda$handle$0(PacketSendServerCommand.java:41) ~[?:1.15-4.0.3-alpha {re:classloading}
16.04 20:28:06 [Server] net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:? {re:classloading}
16.04 20:28:06 [Server] mcjty.lib.network.PacketSendServerCommand.handle(PacketSendServerCommand.java:40) ~[?:1.15-4.0.3-alpha {re:classloading}
16.04 20:28:06 [Server] net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:? {re:classloading}
16.04 20:28:07 [Multicraft] Skipped 27 lines due to rate limit (100/s)
16.04 20:28:07 [Server] Server thread/FATAL Error executing task on Server
16.04 20:28:07 [Server] INFO java.lang.NullPointerException: null
16.04 20:28:07 [Server] mcjty.rftoolsstorage.craftinggrid.StorageCraftingTools.match(StorageCraftingTools.java:153) ~[?:1.15-1.0.3-alpha {re:classloading}
16.04 20:28:07 [Server] mcjty.rftoolsstorage.craftinggrid.StorageCraftingTools.tryRecipe(StorageCraftingTools.java:63) ~[?:1.15-1.0.3-alpha {re:classloading}
16.04 20:28:07 [Server] mcjty.rftoolsstorage.craftinggrid.StorageCraftingTools.lambda$testCraftItems$3(StorageCraftingTools.java:293) ~[?:1.15-1.0.3-alpha {re:classloading}
16.04 20:28:07 [Server] java.util.Optional.map(Optional.java:215) ~[?:1.8.0_241 {}
16.04 20:28:07 [Server] mcjty.rftoolsstorage.craftinggrid.StorageCraftingTools.testCraftItems(StorageCraftingTools.java:268) ~[?:1.15-1.0.3-alpha {re:classloading}
16.04 20:28:07 [Server] mcjty.rftoolsstorage.modules.modularstorage.blocks.ModularStorageTileEntity.craft(ModularStorageTileEntity.java:136) ~[?:1.15-1.0.3-alpha {re:classloading}
16.04 20:28:07 [Server] mcjty.rftoolsstorage.craftinggrid.StorageCraftingTools.craftFromGrid(StorageCraftingTools.java:330) ~[?:1.15-1.0.3-alpha {re:classloading}
16.04 20:28:07 [Server] mcjty.rftoolsstorage.setup.CommandHandler.lambda$registerCommands$5(CommandHandler.java:86) ~[?:1.15-1.0.3-alpha {re:classloading}
16.04 20:28:07 [Server] mcjty.lib.McJtyLib.handleCommand(McJtyLib.java:96) ~[?:1.15-4.0.3-alpha {re:classloading}
16.04 20:28:07 [Server] mcjty.lib.network.PacketSendServerCommand.lambda$handle$0(PacketSendServerCommand.java:41) ~[?:1.15-4.0.3-alpha {re:classloading}
16.04 20:28:07 [Server] net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:? {re:classloading}
16.04 20:28:07 [Server] mcjty.lib.network.PacketSendServerCommand.handle(PacketSendServerCommand.java:40) ~[?:1.15-4.0.3-alpha {re:classloading}
16.04 20:28:07 [Server] net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:? {re:classloading}
16.04 20:28:07 [Server] java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_241 {}
16.04 20:28:07 [Server] net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:? {re:classloading}
16.04 20:28:07 [Server] net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:? {re:classloading}
16.04 20:28:07 [Server] net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:? {re:classloading}
16.04 20:28:07 [Server] net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.0.0-milestone.1-service.jar:? {}
16.04 20:28:07 [Server] net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.0.0-milestone.1-service.jar:? {}
16.04 20:28:07 [Server] net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:? {}
16.04 20:28:07 [Server] net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:? {re:classloading}
16.04 20:28:07 [Server] net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78) ~[?:? {re:mixin,re:classloading,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:MixinForgeNetworkHooks,pl:mixin:A}
16.04 20:28:07 [Server] java.util.Optional.map(Optional.java:215) ~[?:1.8.0_241 {}
16.04 20:28:07 [Server] net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78) ~[?:? {re:mixin,re:classloading,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:MixinForgeNetworkHooks,pl:mixin:A}
16.04 20:28:07 [Server] net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1279) ~[?:? {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer,pl:mixin:A}
16.04 20:28:07 [Server] net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:? {re:classloading,pl:runtimedistcleaner:A}
16.04 20:28:07 [Server] net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:? {re:classloading,pl:runtimedistcleaner:A}
16.04 20:28:07 [Server] net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:? {re:classloading}
16.04 20:28:07 [Server] net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:? {re:classloading}
16.04 20:28:07 [Server] net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:? {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
16.04 20:28:07 [Server] net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:? {re:mixin,re:classloading}
16.04 20:28:07 [Server] net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:? {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
16.04 20:28:07 [Server] net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:? {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
16.04 20:28:07 [Server] net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:? {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
16.04 20:28:07 [Server] net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:? {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
16.04 20:28:07 [Server] net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:? {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
16.04 20:28:07 [Server] net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:? {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
16.04 20:28:07 [Server] net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) [?:? {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
16.04 20:28:07 [Server] net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:? {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
16.04 20:28:07 [Server] java.lang.Thread.run(Thread.java:748) [?:1.8.0_241 {}
16.04 20:28:08 [Server] Server thread/FATAL Error executing task on Server
16.04 20:28:08 [Server] INFO java.lang.NullPointerException: null
16.04 20:28:08 [Server] mcjty.rftoolsstorage.craftinggrid.StorageCraftingTools.match(StorageCraftingTools.java:153) ~[?:1.15-1.0.3-alpha {re:classloading}
16.04 20:28:08 [Server] mcjty.rftoolsstorage.craftinggrid.StorageCraftingTools.tryRecipe(StorageCraftingTools.java:63) ~[?:1.15-1.0.3-alpha {re:classloading}
16.04 20:28:08 [Server] mcjty.rftoolsstorage.craftinggrid.StorageCraftingTools.lambda$testCraftItems$3(StorageCraftingTools.java:293) ~[?:1.15-1.0.3-alpha {re:classloading}
16.04 20:28:08 [Server] java.util.Optional.map(Optional.java:215) ~[?:1.8.0_241 {}
16.04 20:28:08 [Server] mcjty.rftoolsstorage.craftinggrid.StorageCraftingTools.testCraftItems(StorageCraftingTools.java:268) ~[?:1.15-1.0.3-alpha {re:classloading}
16.04 20:28:08 [Server] mcjty.rftoolsstorage.modules.modularstorage.blocks.ModularStorageTileEntity.craft(ModularStorageTileEntity.java:136) ~[?:1.15-1.0.3-alpha {re:classloading}
16.04 20:28:08 [Server] mcjty.rftoolsstorage.craftinggrid.StorageCraftingTools.craftFromGrid(StorageCraftingTools.java:330) ~[?:1.15-1.0.3-alpha {re:classloading}
16.04 20:28:08 [Server] mcjty.rftoolsstorage.setup.CommandHandler.lambda$registerCommands$5(CommandHandler.java:86) ~[?:1.15-1.0.3-alpha {re:classloading}
16.04 20:28:08 [Server] mcjty.lib.McJtyLib.handleCommand(McJtyLib.java:96) ~[?:1.15-4.0.3-alpha {re:classloading}
16.04 20:28:08 [Server] mcjty.lib.network.PacketSendServerCommand.lambda$handle$0(PacketSendServerCommand.java:41) ~[?:1.15-4.0.3-alpha {re:classloading}
16.04 20:28:08 [Server] net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:? {re:classloading}
16.04 20:28:08 [Server] mcjty.lib.network.PacketSendServerCommand.handle(PacketSendServerCommand.java:40) ~[?:1.15-4.0.3-alpha {re:classloading}
16.04 20:28:08 [Server] net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:? {re:classloading}
16.04 20:28:08 [Server] java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_241 {}
16.04 20:28:08 [Server] net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:? {re:classloading}
16.04 20:28:08 [Server] net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:? {re:classloading}
16.04 20:28:08 [Server] net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:? {re:classloading}
16.04 20:28:08 [Server] net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.0.0-milestone.1-service.jar:? {}
16.04 20:28:08 [Server] net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.0.0-milestone.1-service.jar:? {}
16.04 20:28:08 [Server] net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:? {}
16.04 20:28:08 [Server] net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:? {re:classloading}
16.04 20:28:08 [Server] net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78) ~[?:? {re:mixin,re:classloading,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:MixinForgeNetworkHooks,pl:mixin:A}
16.04 20:28:08 [Server] java.util.Optional.map(Optional.java:215) ~[?:1.8.0_241 {}
16.04 20:28:08 [Server] net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78) ~[?:? {re:mixin,re:classloading,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:MixinForgeNetworkHooks,pl:mixin:A}
16.04 20:28:08 [Server] net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1279) ~[?:? {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer,pl:mixin:A}
16.04 20:28:08 [Server] net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:? {re:classloading,pl:runtimedistcleaner:A}
16.04 20:28:08 [Server] net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:? {re:classloading,pl:runtimedistcleaner:A}
16.04 20:28:08 [Server] net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:? {re:classloading}
16.04 20:28:08 [Server] net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:? {re:classloading}
16.04 20:28:08 [Server] net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:? {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
16.04 20:28:08 [Server] net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:? {re:mixin,re:classloading}
16.04 20:28:08 [Server] net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:? {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
16.04 20:28:08 [Server] net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:? {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
16.04 20:28:08 [Server] net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:? {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
16.04 20:28:08 [Server] net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:? {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
16.04 20:28:08 [Server] net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:? {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
16.04 20:28:08 [Server] net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:? {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
16.04 20:28:08 [Server] net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:693) [?:? {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
16.04 20:28:08 [Server] net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:? {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
16.04 20:28:08 [Server] java.lang.Thread.run(Thread.java:748) [?:1.8.0_241 {}

**Comment by McJty** [comment]
Please don't make tickets containing only a stacktrace. I need at leat version numbers and what exactly you were doing

**Comment by BedrockLegends** [comment]
rftoolsstorage-1.15-1.0.3-alpha. and I was not the one doing it, so not sure
