### ISSUE TITLE
Storage Module Desyncs, Dupes, and Other Wackiness.

### ISSUE THREAD

**Issue by VT-14** [McJtyMods/RFToolsStorage#15]
I've encountered a series of problems with the Storage Modules.  All tests have been performed on a single player world in a creative mode test world with items spawned from JEI.
* In a custom modpack (survival world) they simply didn't work; I put a Tier-2 Storage Module in a Modular Storage, but it wouldn't accept any items.  I later created a new test modpack comprised of only JEI and RFTools Storage (plus dependencies), and got even weirder issues.
* First, it seemed like it just didn't work at all still.  I couldn't shift click or drag and drop items into a Modular Storage.  I also couldn't hopper into it.
* A few minutes later on the same play session I started getting a desync.  When I inserted items it seemed to do nothing, but closing and reopening the GUI caused the items to disappear from my inventory and appear in the Modular Storage.  Hoppers seemed to work properly, and extracting these items seemed to sync properly.
* I wanted to test the Storage Scanner, but didn't have any power available.  I added RFTools Power and restarted the modpack.  After testing the Storage Scanner (which seemed to work fine with a very brief test) I went back to testing the Modular Storage.  Items were still dysyncing on insertion, but were no longer being removed from my inventory, allowing me to keep the versions in my inventory and extracting duplicated versions out of the Modular Storage.
* Through all of these tests I was unable to insert a Storage Module into a Tablet.  I haven't tried charging the tablet yet so it could just be user error.

Versions:
Minecraft: 1.15.2
Forge: 31.2.5
McJtyLib: 4.1.0 beta
RFTools Storage: 1.1.3 beta
RFTools Base: 1.1.1 beta
RFTools Power: 2.1.1 beta
JEI: 6.0.0.4

First Session Forge Logs: https://gist.github.com/VT-14/eac3fa08b5b1cbbbeaf077f73ac7cd2a
Second Session Forge Logs: https://gist.github.com/VT-14/174c4e4df9393d499bccae75ff8184bd
Manual Debug Crash: https://gist.github.com/VT-14/5b8594575f5493ca407232727a11519c

**Comment by McJty** [comment]
Inserting a storage module into a tablet isn't implemented yet. As to the other problems. Very weird. I'll try to see if I can reproduce it somehow

**Comment by McJty** [comment]
Ok. I can reproduce it. Seems something got broken. I'm on it

**Comment by McJty** [comment]
I think I fixed it. Will test and release later today or tomorrow. Thanks for reporting
