### ISSUE TITLE
[1.16.2] Crash when hovering over a crafted storage module

### ISSUE THREAD

**Issue by WhitePhant0m** [McJtyMods/RFToolsStorage#19]
When hovering over a storage module I crafted I crashed, [Crash Log](https://pastebin.com/qkhUchif)

**Comment by McJty** [comment]
There appears to be some mod adding a mixin there:

	at net.minecraft.nbt.CompoundNBT.func_186857_a(CompoundNBT.java:133) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches CompoundNBT Transformer,pl:mixin:APP:kubejs.mixins.json:CompoundNBTMixin,pl:mixin:A}

I don't know what kubejs is but can you also reproduce this crash without that mod? If not then the bug is with that mod and not with RFToolsStorage

**Comment by WhitePhant0m** [comment]
https://pastebin.com/hW6T4KYa
Still crashes with just dependency mods and JEI

Edit: Closed by accident
Edit2:
![image](https://user-images.githubusercontent.com/33400200/92018817-5232ef80-ed5e-11ea-9453-94ec652d8c29.png)

**Comment by McJty** [comment]
I'll check it out

**Comment by McJty** [comment]
Should be fixed with latest release
