### ISSUE TITLE
[1.14.4] Storage scanner dupe same as RFTools issue #1583

### ISSUE THREAD

**Issue by KajesLorian** [McJtyMods/RFToolsStorage#20]
Minecraft Version: 1.14.4
Forge Version: 28.2.0
RFToolsStorage Version: rftoolsstorage-1.14-0.0.7-alpha

Place Storage scanner and scan all chests in area selected.
Items in chests show up twice. (a stack of 22 items will show up as 44 items)
Stacks over 63 will show up as invisible because of issue #4 

Also effects modded storage like Storage Drawers in the same manner.

Link to previous issue: https://github.com/McJtyMods/RFTools/issues/1583

**Comment by McJty** [comment]
1.14.4 is unsupported. It's too old
