### ISSUE TITLE
[1.16.2] Duplication glitch on modular storage with stackable items

### ISSUE THREAD

**Issue by ChrisJacobsJr** [McJtyMods/RFToolsStorage#21]
Minecraft Version: 1.16.2
Rftools Storage Version: 1.16.2-2.0.5
Forge version: 33.0.61

Steps to reproduce:
Place modular storage
add in tier 2 storage card module
place stackable (64) item or block inside modular storage
hold shift and left click on the item several times. The item will double until it reaches 64.

**Comment by McJty** [comment]
Woo. That's a good catch. I'll try to fix that asap

**Comment by McJty** [comment]
Fixed. It was actually also a problem in 1.15.2 and it also affected many blocks in RFTools and XNet. Not only the modular storage. Thanks for reporting!
