### ISSUE TITLE
Storage Scanner bug with middle click

### ISSUE THREAD

**Issue by Rithenar** [McJtyMods/RFToolsStorage#22]
I had just finished putting all my stuff into a Modular Storage with a tier 3 card in it and, out of force of habit, I middle clicked (sort storage) on the storage GUI.  Everything that was stored jumped into my inventory deleting whatever didn't fit, including the card with all it's contents.

I am using the ATM 6 modpack current version which has 1.16-2.0.4-beta version of RFTools Storage and MouseTweaks-2.13-mc1.16.2 for Inventory sorting

**Comment by McJty** [comment]
Update the mods please. I think this is fixed

**Comment by jubalearly** [comment]
This exact same thing just happened to me. 1.16.3

Rftools Storage 1.16-2.0.5
Crafting tweaks 1.16.3-12.2.0
Inventory tweaks renewed 1.16.2-1.0.0
mouse tweaks 2.13-mc1.16.2 

All above at latest versions listed on twitch launcher.

**Comment by McJty** [comment]
This is an interaction bug with inventory tweaks. The upcoming release will have a workaround for this that hopefully works
