### ISSUE TITLE
Storage Scanner Crashing Server 1.16.4

### ISSUE THREAD

**Issue by ClaudiusMinimus** [McJtyMods/RFToolsStorage#29]
Minecraft: 1.16.4
Forge: 35.1.12
RFToolsStorage: 1.16-2.0.7
Our server has crashed three times this morning. One of the players on my server reported:
> ok so on the sic server mymo gave me a storage scanner and a pitiful generator...when we tried to use it it crashes the server..3 times.
on my server it seems to work fine, no crashes.  but on mine i only have 10 storage, your server i have 30ish...might be too much communications?

https://pastebin.com/QEjEupZt

**Comment by ClaudiusMinimus** [comment]
Another player told me he thought the crash happened when the sort button was pressed. I have a few inventory tweak mods in the pack, so I'm looking at that too. 

BTW: Here is a link to the pack https://www.curseforge.com/minecraft/modpacks/survival-in-chaos/files/3136503

**Comment by McJty** [comment]
This is actually a bug in cech12.ceramicbucket. They are crashing while trying to get the name of the item. Please report to them. It's crashing inside ItemStack.getDisplayName() for their item
