### ISSUE TITLE
Weird Tool tip Glitching with the Modular Storage

### ISSUE THREAD

**Issue by Halfdeaf** [McJtyMods/RFToolsStorage#3]
The tooltip goes wild on the Storage Module when inside the Modular Storage it changes between a few items that are stored on the module. This does not happen with the Storage Module in the player inventory.

![2019-12-05_01 54 27](https://user-images.githubusercontent.com/48191482/70197355-7f853b00-1703-11ea-9c66-e1ad0c1f615f.png)

**Comment by McJty** [comment]
Will be fixed next release of McJtyLib
