### ISSUE TITLE
Modular Storage says it needs to be unlocked to access the crafting grid, but it works fine when locked

### ISSUE THREAD

**Issue by aaronhowser1** [McJtyMods/RFToolsStorage#30]
![image](https://user-images.githubusercontent.com/15698722/102534629-b1e2ab80-406c-11eb-8140-66ebaf8e7a19.png)
![image](https://user-images.githubusercontent.com/15698722/102534632-b6a75f80-406c-11eb-9a72-f322638c10e8.png)
![image](https://user-images.githubusercontent.com/15698722/102534641-ba3ae680-406c-11eb-9ca1-8a7d352bcfda.png)

Additionally, the tooltips are on top of each other
![image](https://user-images.githubusercontent.com/15698722/102534689-ccb52000-406c-11eb-8a10-82dc6de35fea.png)

This is using `rftoolsstorage-1.16-2.0.7`

**Comment by aaronhowser1** [comment]
Honestly, I think it's kind of weird that it apparently needs to be unlocked to use the crafting grid. When unlocked, you can't access the items in the Storage. That kind of defeats the whole point, right?
![image](https://user-images.githubusercontent.com/15698722/102534988-2d445d00-406d-11eb-98b8-f7e17e3154fa.png)

**Comment by McJty** [comment]
I'll check this out

**Comment by McJty** [comment]
Various bugs related to this fixed in the next release
