### ISSUE TITLE
1.16.4 Modular Storage not compacting like items

### ISSUE THREAD

**Issue by OutcastZeroOne** [McJtyMods/RFToolsStorage#33]
the button for "Compact equal stacks" dosent seem to do anything. i have to manually go in and compact stacks of items to make room and just generally tidy up the storage.
![Screen Shot 2021-01-03 at 09 41 14](https://user-images.githubusercontent.com/8162248/103486963-79ee9e80-4db6-11eb-9169-b4f9cce8e18d.png)

![2021-01-03_11 21 04](https://user-images.githubusercontent.com/8162248/103486937-59264900-4db6-11eb-92d0-f85aa8fd56ee.png)

**Comment by choekstr** [comment]
This is still an issue as of Oct 05 2021 using these versions: 
![image](https://user-images.githubusercontent.com/161085/136058136-a2f081b3-e1e0-4dcd-b489-cf8694291fee.png)

**Comment by McfarlaneRob** [comment]
Also encountering this problem with below versions:

- rftoolsbase-1.16-2.1.2
- rftoolsstorage-1.16-2.0.17
- rftoolsutility-1.16-3.1.9

**Comment by McJty** [comment]
yes this is not implemented yet in 1.16+. One of the things on my huuuuge todo

**Comment by McJty** [comment]
Will be fixed next release
