### ISSUE TITLE
Config Broken on new versions of forge for 1.16.5

### ISSUE THREAD

**Issue by ModernGamingWorld** [McJtyMods/RFToolsStorage#41]
Your RftoolsStorage config is creating a .bak when using the new version of 1.16.5

if you look at this issue, it goes into some detail on whats happening https://github.com/ShetiPhian/Localizations-and-Issues/issues/293

**Comment by McJty** [comment]
Why did you close this?

**Comment by ModernGamingWorld** [comment]
I closed this cause Mod devs kept telling me I was posting false issue reports when this is happening on tons of mods

https://github.com/NillerMedDild/Enigmatica6/issues/1396
