### ISSUE TITLE
Wrong amount of item in storage scanner

### ISSUE THREAD

**Issue by Sloweneuh** [McJtyMods/RFToolsStorage#45]
For example it says I have 37 diamond axes in my storage but I only have one. latest version of rftoolsstorage for 1.16.5

**Comment by McJty** [comment]
Please.... I can't do anything with a report like this. What version? Screenshots? What did you do? What storage are connected?

**Comment by Sloweneuh** [comment]
I'm sorry. I can't provide screenshots i'm at school but my storage is composed of exclusively modular storages, and maybe there is 37 of them. Could be related to this issue : #42

**Comment by McJty** [comment]
And version?

**Comment by Sloweneuh** [comment]
I said it was latest for 1.16.5

**Comment by McJty** [comment]
Well 'latest' is not a version. If I later look back at this ticket I have no clue what latest will be back then. Always specify exact versions. But really I need screenshots of your setup and GUI

**Comment by Sloweneuh** [comment]
Version 2.0.11. I will try to give you a screenshot in a few hours when I get home

**Comment by Sloweneuh** [comment]
Well I found out where the problem is, it was just me being dumb and had copy paste the storage modules with the card inside in creative while testing. Sorry for wasting your time.
