### ISSUE TITLE
[1.15] Modular Storage is showing inventory in wrong position

### ISSUE THREAD

**Issue by davqvist** [McJtyMods/RFToolsStorage#5]
See screenshot. https://imgur.com/a/z5e2ipN
Also you can't move the items
GUI scale is 3 btw, as that might be relevant.

**Comment by McJty** [comment]
Can reproduce this. Will fix this later

**Comment by Knito58** [comment]
I came here to report this and it was already done :)

**Comment by McJty** [comment]
I have fixed this and will release a fixed version later today
