### ISSUE TITLE
Extraction from personal/locked inventories is possible with the Storage Scanner

### ISSUE THREAD

**Issue by NielsPilgaard** [McJtyMods/RFToolsStorage#53]
Using [RFToolsStorage - 1.16-2.0.13](https://www.curseforge.com/minecraft/mc-mods/rftools-storage/files/3402865)

**Describe the bug**
When Placing Storage Scanner from RFTools near Personal Chest from Mekanism (in range of it) and placing some items in it (from example 9 diamonds), you can craft with those items without losing them (so you can have infinity diamonds for example).

**Screenshots**
Here is a video! (PS: Sorry for horrible quality... I'm not in home and was sending it with internet from my phone :v)
https://youtu.be/eIgNlMe77Us

**Comment by McJty** [comment]
That's most likely a bug in Mekanism as far as I know. RFTools Storage is correctly following the IItemHandler API by first doing a simulate extraction and if that works the real extraction

**Comment by NielsPilgaard** [comment]
After trying to reproduce it myself, I discovered that it only happens if the locked inventory is marked as Routable - If it's not marked as Routable it works very well.

**Comment by NielsPilgaard** [comment]
This is no longer an issue 👍
