### ISSUE TITLE
Crash - Modular Storage / Remote Storage Module

### ISSUE THREAD

**Issue by nirakoji** [McJtyMods/RFToolsStorage#54]
https://pastebin.com/VdA64cQt

Tinkering from Creative mode. Happens both with shift-click as well as drag-and-drop.
![image](https://user-images.githubusercontent.com/69447149/134709587-78de3b21-76de-47be-b5d1-5a6b3e103430.png)

Remote Storage Module was pulled from creative tab.
Minecraft 1.16.5 / Forge 36.2.4
Crash to desktop.

**Comment by McJty** [comment]
The remote storage module is not implemented yet. Don't pull it from creative and use like that

**Comment by osirisgothra** [comment]
someone should really tag the tooltip with WIP :/
