### ISSUE TITLE
Crash when placing storage scanner

### ISSUE THREAD

**Issue by Thanatos0173Unnoficial** [McJtyMods/RFToolsStorage#57]
I make a Storage Scanner in my Minecraft World (in 1.16.5 forge), but when I place it, my game instantly crash.  I try to re-log on my world, but it make me crash again, so I can't reconnect. Here the crash log:
[crash-2021-11-05_20.06.18-client.txt](https://github.com/McJtyMods/RFToolsStorage/files/7488401/crash-2021-11-05_20.06.18-client.txt)
Here is all my mods:
![image](https://user-images.githubusercontent.com/93793013/140566427-4d32147f-c272-463b-8a38-7109180c3be0.png)

**Comment by McJty** [comment]
Update McJtyLib. It's too old
