### ISSUE TITLE
Server disconnects user when trying to pick up storage card

### ISSUE THREAD

**Issue by SirEndii** [McJtyMods/RFToolsStorage#59]
When I try to pick up a storage card from a Modular Storage, the client disconnects from the client.
This only happens when the card has a decent amount of items.
Luckily, the card is back in the block when I rejoin.

Server message : `[02.02 17:32:18] [Disconnect] Srendi has disconnected, reasonInternal Exception: io.netty.handler.codec.DecoderException: Value 198 is larger than limit 128`
![image](https://user-images.githubusercontent.com/67484093/152207185-30e359fd-9db0-4f6f-9829-d629f781c79c.png)

It's not that bad, I can still rejoin and just empty the card a bit. But this is quite annoying when you try to upgrade the card.

**Comment by SirEndii** [comment]
Forgot to add versions
1.18.1 - Forge 39.0.64
RFTools Storage - 1.18-3.0.5

**Comment by McJty** [comment]
Can you give me some logs of when this happens?

**Comment by SirEndii** [comment]
ofc
The snippet of the server log: https://pastebin.com/YTLnwc0G
I tried this two times.

Client log: https://pastebin.com/R53AT4VL
I tried it at 20:19:00
But at this time, there isn't anything in the log containing anything related to this issue.

**Comment by winsrp** [comment]
same happened to me, on a local server

**Comment by ChrisLane** [comment]
I've just come across the same issue trying to take my tier 2 storage module from the modular storage block.
Contents of module: 138/200
Server error:
```
[net.minecraft.server.network.ServerGamePacketListenerImpl/]: ChrisLane lost connection: Internal Exception: io.netty.handler.codec.DecoderException: Value 139 is larger than limit 128
```

Minecraft: 1.18.2
Forge: 40.0.54
RFToolsStorage: 3.0.7
Modpack: All The Mods 7 0.3.12

**Comment by McJty** [comment]
I'll check it out

**Comment by TheMrCaveman** [comment]
We have the same issue. Need any more info?

**Comment by McJty** [comment]
I mostly need more time. So if you can send me some time that would be perfect

**Comment by SirEndii** [comment]
Sending time... damn that would be perfect :P

**Comment by McJty** [comment]
Ok, I know the problem and it's a stupid vanilla limitation. Vanilla can't handle a container where suddenly (in one operation) more then 128 items disappear from the container. So when your storage card has more then 128 items and you remove it from the container then more then 128 items will be gone. When the server sends that info to the client it hits a limit of 128 changed slots.

I currently don't yet know how to solve this. Will have to think about this

**Comment by McJty** [comment]
Ok, I almost have a solution. I fixed the crash but now client-side some info is wrong. I'll continue with this tomorrow

**Comment by SirEndii** [comment]
Nice to hear!

**Comment by McJty** [comment]
Fixed (by adding only one line of code)
