### ISSUE TITLE
Transparency Issue on tool tip for modular storage 1.15

### ISSUE THREAD

**Issue by winsrp** [McJtyMods/RFToolsStorage#6]
rftoolsbase-1.15-1.0.0-alpha
rftoolsstorage-1.15-1.0.1-alpha

Fill the storage with several rows of stackable items 

When moving the cursor over an item you can see the transparency issue (the numbers of the stacks under the tooltip seems to show as black text on top of the tool tip)

![image](https://user-images.githubusercontent.com/13665046/74262101-e0139400-4cc1-11ea-9e53-f662a059ac4a.png)

Also tooltips on the buttons from below seem to overlap with items on some of the rows of stored stacks

![image](https://user-images.githubusercontent.com/13665046/74262216-13eeb980-4cc2-11ea-8577-987ea228d2b8.png)

**Comment by McJty** [comment]
Will be fixed next release
