### ISSUE TITLE
[1.18.1] Crash when shifting recipe in storage scanner from NEI

### ISSUE THREAD

**Issue by meson11** [McJtyMods/RFToolsStorage#60]
Modpack: All The Mods 7 - 0.2.41
[crash-2022-02-20_23.12.03-client.txt](https://github.com/McJtyMods/RFToolsStorage/files/8105037/crash-2022-02-20_23.12.03-client.txt)

**Comment by McJty** [comment]
This looks like a bug in NEI to be honest. With JEI it works correctly and it seems NEI is giving wrong slot numbers. Please report to them
