### ISSUE TITLE
[Bug][Mod Interaction]

### ISSUE THREAD

**Issue by Targren** [McJtyMods/RFToolsStorage#61]
RFtools Storage Version:  2.0.15
Draconic Evolution: 3.0.18.428 

To Reproduce: 

1. Place Storage Scanner and Power Cell 
2. Place Draconic Chest 2 Blocks from Scanner, and place recognizable test item inside
3. Set Scanner Radius to 2
4. Draconium Chest doesn't show up in the list

**Comment by McJty** [comment]
Looks like a bug in Draconic Evolution then
