### ISSUE TITLE
[1.18.2] Fatal Crash with Remote Storage Module

### ISSUE THREAD

**Issue by HalcyonSeas73** [McJtyMods/RFToolsStorage#62]
RFToolsStorage version: 1.18-3.0.7
RFToolsUtility version (if relevent): 1.18-4.0.12
RFToolsBase version: 1.18-3.0.7
McJtyLib version: 1.18-6.0.11

The game crashes when trying to add the Remote Storage Module to a Modular Storage Block, and cannot be added to a Tablet.

Log: https://paste.ee/p/ZBFTA

**Comment by McJty** [comment]
Umm where did you get a remote storage module from? That's not implemented yet which is why it has no recipe

**Comment by HalcyonSeas73** [comment]
Via JEI, testing before I use it in my "play" world. I didn't know it wasn't implemented yet. Good to know!

**Comment by Jkosio23** [comment]
Might be a good idea to put [wip] in the tooltip somewhere like with the Crafting Manager
