### ISSUE TITLE
Unable to run client from source

### ISSUE THREAD

**Issue by ChrisLane** [McJtyMods/RFToolsStorage#65]
I'm trying to run the Minecraft client in my IDE from the RFToolsStorage source.
It would seem that the dependencies in the build.gradle and the maven repo file are outdated since I get errors about incorrect McJtyMods dependency versions.

`Mod rftoolsstorage requires mcjtylib 1.18-6.0.11 or above` but the highest version I could find at https://maven.k-4u.nl/com/github/mcjty/mcjtylib/ was 1.18-6.0.10.24

`Mod rftoolsstorage requires rftoolsbase 1.18-3.0.7 or above` but the highest version I could find at https://maven.k-4u.nl/com/github/mcjty/rftoolsbase/ was 1.18-3.0.6-7

Could you please update the maven repository and build files to fix this?

**Comment by McJty** [comment]
Yes I need to fix those. I don't have that problem because I put everything in a big multi mod project

**Comment by McJty** [comment]
Fixed
