### ISSUE TITLE
[1.19.2] Tablet (scanner) Crafting Grid Improperly Highlighted

### ISSUE THREAD

**Issue by HalcyonSeas73** [McJtyMods/RFToolsStorage#68]
Minecraft version: 1.19.2
Forge: 43.0.11
McJtyLib: 1.19-7.0.2
RFToolsBase: 1.19.1- 4.0.2
RFToolsStorage: 1.19-4.0.0

Adding a recipe via the crafting grid, and if there aren't enough ingredients, the wrong item is highlighted. Additionally, even if there are enough ingredients, the result remains highlighted in red.

![Untitled](https://user-images.githubusercontent.com/84727791/184793992-2bb647d7-d1f8-4db1-bf2f-05d558139ce8.png)

![Untitled2](https://user-images.githubusercontent.com/84727791/184794351-e83e7436-0809-4158-8375-5b23fa5dd796.png)

![Untitled3](https://user-images.githubusercontent.com/84727791/184794373-ed6ae2f5-06e9-47a6-a233-f926a6d6cf14.png)

![Untitled4](https://user-images.githubusercontent.com/84727791/184794392-ab61a067-3c4b-4e66-ad2a-8be28251e894.png)

**Comment by McJty** [comment]
Fixed
