### ISSUE TITLE
[1.19.2] Item Durability bar not displaying properly in Modular Storage

### ISSUE THREAD

**Issue by HalcyonSeas73** [McJtyMods/RFToolsStorage#69]
RFTools Storage version: 4.0.1
RFTools Base version: 4.0.3
McJtyLib version: 7.0.2
Forge version: 43.1.1
Minecraft version: 1.19.2

Items with different durability do not render properly in the Modular Storage block. They all show a fully-black durability bar, when the tooltip, inventory, and other mods all indicate the item's durability properly. 

![](https://cdn.discordapp.com/attachments/403872061568712705/1016552830661820416/unknown.png)

![](https://cdn.discordapp.com/attachments/403872061568712705/1016598258631573514/unknown.png)

![](https://cdn.discordapp.com/attachments/403872061568712705/1016598324796719164/unknown.png)

**Comment by McJty** [comment]
This will be fixed in the next release of McJtyLib
