### ISSUE TITLE
[1.15.2] Console spam "Error executing task on Server java.lang.NullPointerException: null"

### ISSUE THREAD

**Issue by Boomflex** [McJtyMods/RFToolsStorage#7]
https://pastebin.com/92tuDAD4

RFTools Storage: 1.0.2
Forge: 31.1.27

**Comment by suprra** [comment]
Getting the same on mine

RFTools Storage 1.0.3
Forge 31.1.30

Using curse server All the mods 5 modpack (updated to latest version of Forbidden Arcanus & added building gadgets)

**Comment by McJty** [comment]
Does this still happen with later updates? I cannot reproduce this problem
