### ISSUE TITLE
combine in not working

### ISSUE THREAD

**Issue by DiggityMan420** [McJtyMods/RFToolsStorage#71]
The combine stacks button isnt seem to work on atm7 to the sky 18.x In the modular storage. ive tried it all kinds of ways emty inventorys only 2 items in there full boxes. see pic
![Screenshot_28](https://user-images.githubusercontent.com/45196448/189707745-e2a5a846-9e0a-49d8-9a77-0a9039ad2dcb.jpg)

**Comment by McJty** [comment]
What version of RFTools Storage?

**Comment by DiggityMan420** [comment]
![Screenshot_29](https://user-images.githubusercontent.com/45196448/190233895-8d492005-c2a7-483b-8070-bb47968818f9.jpg)

**Comment by DiggityMan420** [comment]
sorry for  late reply my father passed away yesterday :(

**Comment by McJty** [comment]
I'm very sorry to hear that. My condolences!

**Comment by HalcyonSeas73** [comment]
Same issue as #33 ?

**Comment by McJty** [comment]
Will be fixed next release
