### ISSUE TITLE
[1.19.2] Broken GUI Font Scaling

### ISSUE THREAD

**Issue by HalcyonSeas73** [McJtyMods/RFToolsStorage#73]
RFToolsStorage version: 1.19-4.0.2
RFToolsBase version: 1.19-4.0.3
McJtyLib version: 1.19-7.0.3
Forge version: 43.1.32
Minecraft version: 1.19.2

The recent update to RFToolsBase/RFToolsStorage broke font scaling in the GUI.
![image](https://user-images.githubusercontent.com/84727791/193812435-34c29c81-06d7-425f-b7f4-8cfd2a3143ba.png)

**Comment by McJty** [comment]
Fixed in McJtyLib
