### ISSUE TITLE
[1.19.2 bug] Client crash while viewing storage scanner

### ISSUE THREAD

**Issue by sharkck** [McJtyMods/RFToolsStorage#75]
I was just sitting in the storage scanner screen and the client crashed with the following "Rendering Screen" error:
[crash-2022-11-04_17.52.45-client.txt](https://github.com/McJtyMods/RFToolsStorage/files/9942200/crash-2022-11-04_17.52.45-client.txt)

**Comment by sharkck** [comment]
RFTools Storage version  4.0.2
Forge version 43.1.47

**Comment by McJty** [comment]
I'll check it out

**Comment by sharkck** [comment]
Thanks.  In case it helps, I am using my modpack, Frankfurter 6 on Curseforge if it saves you some time.  Also, anything I can do to help, feel free to ask.  I am also running this on a dedicated server.

**Comment by McJty** [comment]
Fixed in McJtyLib (the bug was there)
