### ISSUE TITLE
Lost all my stuff inside the modular storage

### ISSUE THREAD

**Issue by jamiet9** [McJtyMods/RFToolsStorage#76]
I loaded a tier 4 storage module up and then curiously clicked onto "compact equal stacks" to see what it does, and POOF! Nothing is in the storage module anymore. Everything is gone. I then tried to replicate this with some cobblestone, and sure enough, the cobblestone disappears when I click that button.

**Comment by McJty** [comment]
Version?

**Comment by jamiet9** [comment]
1.10.3.jar this happened in the stoneblock 3 modpack

**Comment by McJty** [comment]
1.10.3 is not a valid version for RFTools Storage. I need more details and a correct version

**Comment by jamiet9** [comment]
oh right, i just assumed that the file name was the version, let me find out for you

**Comment by McJty** [comment]
Well the filename contains the version. But that's not a version for rftools storage. Show me the full filename

**Comment by jamiet9** [comment]
oh, I was looking at refined storage whoops. The version is 1.18-3.0.11.jar

**Comment by McJty** [comment]
Ok. I'll check it out

**Comment by jamiet9** [comment]
thank you :)

**Comment by jamiet9** [comment]
[https://clipchamp.com/watch/KHo01rJzfDB](url) Here is a clip of the issue

**Comment by jamiet9** [comment]
It happens if I click it when it is unlocked

**Comment by McJty** [comment]
And when you lock it again the items remain lost?

**Comment by McJty** [comment]
I fixed it. The problem was that you pressed it when the card was unlocked. That's not supposed to do anything. I fixed it so that it indeed doesn't do anything

**Comment by jamiet9** [comment]
Awsome, that was fast. Thank you :)
