### ISSUE TITLE
Crash after crafting items in the RFTools Storage Tablet in 1.18.2

### ISSUE THREAD

**Issue by Raidobw2** [McJtyMods/RFToolsStorage#78]
Hi, someone at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1990 is crashing after crafting items in the Storage Tablet (which appears linked to a Storage Scanner). I'm not sure if this is due to RFTools Storage... Please let me know if you think it might be something else and thank you in advance

Versions:
rftoolsstorage-1.18-3.0.12.jar
mcjtylib-1.18-6.0.18.jar

Modpack:
FTB Stoneblock 3 v 1.3.0

Log:
https://paste.feed-the-beast.com/view/dac26af8
[crash-2022-11-18_14.24.45-client.txt](https://github.com/McJtyMods/RFToolsStorage/files/10082362/crash-2022-11-18_14.24.45-client.txt)

Other info:
REI is installed

**Comment by McJty** [comment]
This seems to be caused by REI. I would report to them

**Comment by Raidobw2** [comment]
I've done so, thanks a lot! Have a good weekend in advance
