### ISSUE TITLE
Pressing '\' while in the Storage Scanner interface crashes client

### ISSUE THREAD

**Issue by SirLaughy** [McJtyMods/RFToolsStorage#85]
Whenever I accidentally press the \ key while in the storage scanner, my client hard crashes in 1.16.5

**Comment by McJty** [comment]
I need to see a crashlog

**Comment by SirLaughy** [comment]
[crash-2023-11-19_17.58.07-client.txt](https://github.com/McJtyMods/RFToolsStorage/files/13403210/crash-2023-11-19_17.58.07-client.txt)
[crash-2023-11-19_18.28.20-client.txt](https://github.com/McJtyMods/RFToolsStorage/files/13403211/crash-2023-11-19_18.28.20-client.txt)
[crash-2023-11-19_16.30.04-client.txt](https://github.com/McJtyMods/RFToolsStorage/files/13403212/crash-2023-11-19_16.30.04-client.txt)
[crash-2023-11-19_17.19.46-client.txt](https://github.com/McJtyMods/RFToolsStorage/files/13403213/crash-2023-11-19_17.19.46-client.txt)

Here are all 4 crash logs from today (My finger slips a lot)

**Comment by McJty** [comment]
It's crashing in inventory tweaks. Report to them
