### ISSUE TITLE
Modular storage voiding when over max capacity

### ISSUE THREAD

**Issue by suprra** [McJtyMods/RFToolsStorage#9]
I have a lv2 storage module in the unit. Added a bunch of stuff and noticed that I was at max and the items I added disappeared. At max capacity it is still allowing me to shift click in cobblestone but it appears to be voiding. 
If I move the item via mouse it will not insert
here's a quick vid showing it https://gyazo.com/cc0408f4b597ff672fcad9a5ed1f257f

I realise it's quite the needle in a haystack but though I'd at least post the issue so it exists.

Using curse all the mods 5 modpack added to AT Launcher with added building gadgets & updated Forbidden Arcanus

RFTools Storage 1.0.3
Forge 31.1.30

**Comment by mcmanusef** [comment]
I can confirm that this is still an issue that I have also encountered

**Comment by mcmanusef** [comment]
I can confirm this is an issue that I have encountered.

**Comment by McJty** [comment]
What version?

**Comment by mcmanusef** [comment]
I encountered this issue on 1.1.1.  I am updating and trying again with the most recent version right now.

**Comment by McJty** [comment]
Never mind. I can reproduce this

**Comment by McJty** [comment]
Fixed next release
